blank_issues_enabled: false
contact_links:
  - name: Alpha Driver Community Support
    url: https://github.com/evan-palmer/alpha/discussions
    about: Please check out our discussions channel for any questions related to the project!
