/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1
      joint_limits:
        axis_a:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 2.0
        axis_b:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 2.0
        axis_c:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 2.0
        axis_d:
          has_velocity_limits: true
          max_velocity: 1.0
          has_acceleration_limits: true
          max_acceleration: 2.0
        axis_e:
          has_velocity_limits: true
          max_velocity: 0.5
          has_acceleration_limits: true
          max_acceleration: 2.0
