controller_manager:
  ros__parameters:
    update_rate: 225 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    jaws_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - axis_e
      - axis_d
      - axis_c
      - axis_b
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity

jaws_controller:
  ros__parameters:
    joints:
      - axis_a
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
