name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CLANG_TIDY: true

jobs:
  test:
    name: Test Implementation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - IMAGE: rolling-ci
            ROS_DISTRO: rolling
          - IMAGE: humble-ci
            ROS_DISTRO: humble
          - IMAGE: iron-ci
            ROS_DISTRO: iron
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log into registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          DOCKER_IMAGE: ghcr.io/evan-palmer/alpha:${{ matrix.env.IMAGE }}
          CXXFLAGS: >-
            -Wall -Wextra -Wpedantic -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls
          CC: ${{ env.CLANG_TIDY && 'clang' }}
          CXX: ${{ env.CLANG_TIDY && 'clang++' }}
