name: Continuous Integration

on:
  push:
    branches:
      - main
      - 4-feature-gh-actions-docker-pipelines
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test:
    name: Test Implementation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env:
          - IMAGE: rolling-ci
            ROS_DISTRO: rolling
          - IMAGE: humble-ci
            ROS_DISTRO: humble
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log into registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Clang-Tidy
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          container: ghcr.io/evan-palmer/alpha:${{ matrix.env.IMAGE }}
          linter: clang_tidy
          distribution: ${{ matrix.env.ROS_DISTRO }}
          package-name: alpha
          workspace-directory: outputs.ros-workspace-directory-name

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          DOCKER_IMAGE: ghcr.io/evan-palmer/alpha:${{ matrix.env.IMAGE }}
          CXXFLAGS: >-
            -Wall -Wextra -Wpedantic -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls
