name: Docker

on:
  schedule:
    - cron: "0 17 * * 6"
  push:
    branches:
      - main
      - 4-feature-gh-actions-docker-pipelines
  pull_request:
    paths:
      - .docker/**
      - .github/workflows/docker.yaml
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, rolling]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'evan-palmer/alpha') }}
      GH_IMAGE: rdml/alpha:${{ matrix.ROS_DISTRO }}-${{ github.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log into registry
        if: env.PUSH == 'true'
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: .docker/Dockerfile
          build-args: ROS_DISTRO=${{ matrix.ROS_DISTRO }}
          target: ${{ github.job }}
          push: ${{ env.PUSH }}
          no-cache: true
          tags: |
            ${{ env.DH_IMAGE }}

  source:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, rolling]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'evan-palmer/alpha') }}
      GH_IMAGE: rdml/alpha:${{ matrix.ROS_DISTRO }}-${{ github.job }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log into registry
        if: env.PUSH == 'true'
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: .docker/Dockerfile
          build-args: ROS_DISTRO=${{ matrix.ROS_DISTRO }}
          target: ${{ github.job }}
          push: ${{ env.PUSH }}
          no-cache: true
          tags: |
            ${{ env.DH_IMAGE }}
